---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
#shared_mtcars <- SharedData$new(mtcars)

data(txhousing, package = "ggplot2")

tx <- highlight_key(txhousing, ~city)
gg <- ggplot(tx) + geom_line(aes(date, median, group = city))
filter <- bscols(
  filter_select("id", "Select a city", tx, ~city),
  ggplotly(gg, dynamicTicks = TRUE),
  widths = c(12, 12)
)

tx2 <- highlight_key(txhousing, ~city, "Select a city")
gg <- ggplot(tx2) + geom_line(aes(date, median, group = city))
select <- highlight(
  ggplotly(gg, tooltip = "city"), 
  selectize = TRUE, persistent = TRUE
)

bscols(filter, select)

# bscols(widths = c(3, NA),
#        list(
#          filter_checkbox("cyl", "Cylinders", shared_mtcars, ~cyl, inline = TRUE)#,
#          #filter_checkbox("vs", "VS", shared_mtcars, ~vs, inline = TRUE)
#        ),
#       plotly::ggplotly(shared_mtcars %>% 
#                   ggplot(aes(x = wt, y = mpg, group=factor(cyl),
#                              colour = factor(cyl))) + 
#                     geom_point() +
#                     theme(legend.position = "none"))
#                   # geom_histogram(fill = "pale green",
#                   #                color = "black") + 
#                   # theme(legend.position = "none"))
#        # plotly::ggplotly(shared_mtcars %>% 
#        #                    ggplot(aes(x = mpg,group=paste0(cyl,vs))) + 
#        #                    geom_histogram(fill = "pale green",
#        #                                   color = "black") + 
#        #                    theme(legend.position = "none"))
# )
# 
# # bscols(widths = c(3,NA, NA),
# #   list(
# #     filter_checkbox("cyl", "Cylinders", shared_mtcars, ~cyl, inline = TRUE),
# #     filter_select("auto", "Automatic", shared_mtcars, ~ifelse(am == 0, "Yes", "No"))
# #   ),
# #   plotly::ggplotly(shared_mtcars %>% 
# #                           ggplot(aes(x = wt, y= mpg,
# #                                      color = factor(cyl),
# #                                      )
# #                                  ) + 
# #                           geom_point() 
# # #  d3scatter(shared_mtcars, ~wt, ~mpg, ~factor(cyl), width="100%", height=250),
# # #  d3scatter(shared_mtcars, ~hp, ~qsec, ~factor(cyl), width="100%", height=250)
# # ))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

